### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Zarkness** [CPJiNan/AkariLevel#11]
hello, does the plugin support version 1.20.6 and 1.21?

**Comment by CPJiNan** [comment]
Hello,

AkariLevel does not currently support versions 1.20.6 and 1.20.1.

This is because the compatibility of these versions depends on the Taboolib framework. 
We need to wait for its version update to ensure compatibility with 1.20.6 and 1.20.1.

Here is a conversation from the Taboolib community discussing this issue:

![Taboolib](https://github.com/user-attachments/assets/e0d87676-096a-4cc6-959f-d768337de717)

> "皓: Does Taboolib support 1.21 now?"
> "枫溪: Still waiting."
> "枫溪: The underlying work has been completed."

Additionally, you might want to check out the AkariLevel 4.0.4 update. 
This version introduces a new team experience sharing feature. 

We are currently using the DungeonPlus plugin for team integration. 
If you are using a different team plugin, please let me know, and I can look into adding support for it.

Thank you for your understanding and support.

**Comment by Zarkness** [comment]
ok, thank you very much, it's time to wait, and at the moment I'm not using any, because I'm currently configuring the skyblock of my server, when I get with the survival, if I use any I'll tell you.

**Comment by CPJiNan** [comment]
@Zarkness 

After testing, it seems that the 4.0.6 version already supports 1.20.6 and 1.21.
